<template>
  <ComponentPage title="ArtifactCard" :demos="demos">
    <div class="h-64">
      {{ artifacts }}
    </div>

    <template #flow-run>
      {{ artifacts }}
    </template>
  </ComponentPage>
</template>

<script lang="ts" setup>
  import ComponentPage from '@/demo/components/ComponentPage.vue'
  import { useArtifactsMock } from '@/demo/compositions/useArtifactsMock'
  import { DemoSection } from '@/demo/types/demoSection'

  const demos: DemoSection[] = [{ title: 'Flow Run', description: 'An artifact generated by a flow run' }]

  const artifacts = useArtifactsMock(1)
</script>