export type CollectionItem = {
  name: string,
  description: string,
  logoUrl: string,
  returns: string,
  examples: string[],
  documentationUrl: string,
  entrypoint: string,
  installCommand: string,
  parameters: unknown,
  path: string,
  repositoryUrl: string,
  slug: string,
  collectionType: string,
}